name: Azure web app and functions deployment
on: 
  workflow_dispatch:
  push: 
    paths: 
      - 'src/**'
      - '!src/iot**'
      - '.github/workflows/deployWebApplications.yml'

env:
  AZURE_FUNCTIONAPP_NAME: 'fnapp-homeproject'  # set this to the resource name as created in the bicep file
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/api'
  DOTNET_VERSION: '6.0.x' # needs to be updated when you update the dotnet framework to use. 

jobs: 
  Build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout self
        uses: actions/checkout@v3
      
      - name: Azure login
        uses: Azure/login@v1.4.5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      # - name: Test
      #   run: dotnet test --logger trx --results-directory "TestResults-${{ env.DOTNET_VERSION }}"

      # - name: Upload dotnet test results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dotnet-results-${{ env.DOTNET_VERSION }}
      #     path: TestResults-${{ env.DOTNET_VERSION }}
      #   if: ${{ always() }}
      
      - name: Build
        run: dotnet build --source ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
    
      - name: Build and deploy web app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/webapp"
          output_location: "wwwroot"
