name: Azure web app and functions deployment
on: 
  workflow_dispatch:
  push: 
    paths: 
      - 'src/**'
      - '!src/iot**'
      - '.github/workflows/deployWebApplications.yml'

jobs: 
  Build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout self
        uses: actions/checkout@v3

      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/webapp" # App source code path
          api_location: "src/webappApi" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
